apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: projectcontour

commonLabels:
  env: dev
  cloud: kind
  region: localhost # cloud provider region
  deployment: local

resources:
  - ./contour.yaml