apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-system

commonLabels:
  env: dev                # env usually one of dev, test or prod
  cloud: kind             # typically aws, gcp, azure ..etc
  region: localhost       # cloud provider region
  deployment: local       # deployment instance ex. staging, prod-1, prod-2...

bases:
- github.com/zalando/postgres-operator/manifests?ref=v1.5.0

resources:
  - ./namespace.yaml