apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-system

commonLabels:
  env: dev
  cloud: kind
  region: localhost # cloud provider region
  deployment: local


bases:
- github.com/zalando/postgres-operator/manifests?ref=v1.5.0

resources:
  - ./namespace.yaml